
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'ba_twitter_analysis'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'ba_twitter_analysis'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  ba_twitter_analysis:
    analyses_month:
      +materialized: table
      +schema: analyses_month
    analyses_week:
      +materialized: table
      +schema: analyses_week
    source:
      +materialized: incremental  
      +schema: src
    curated:
      +materialized: incremental  
      +schema: curated
    staging:
      +materialized: incremental  
      +schema: staging
    external:
      +materialized: incremental  
      +schema: external
    dev:
      +schema: bachelor_analytics

seeds:
  ba_twitter_analysis:
    categories:
      +enabled: true
      +schema: seed
      +full_refresh: true