version: 2

models:

  - name: 00_interactions_referrers
    description: >
      Enhanced version of the interactions table that includes information about the
      users being referenced in each interaction. Adds refers_to_user_id by joining
      back to the interactions table.
    columns:
      - name: tweet_id
        description: Unique identifier for the tweet
      - name: user_id  
        description: User who created the tweet
      - name: source_application
        description: Application used to post tweet
      - name: retweet_count
        description: Number of retweets
      - name: favourite_count
        description: Number of likes/favourites
      - name: lang
        description: Tweet language
      - name: type
        description: Type of interaction (tweet, retweet, etc)
      - name: hashtags
        description: Array of hashtags used
      - name: urls
        description: Array of URLs included
      - name: mentioned_ids
        description: Array of mentioned user IDs
      - name: raw_text
        description: Original unprocessed tweet text
      - name: text
        description: Cleaned tweet text with URLs removed
      - name: refers_to
        description: ID of referenced tweet if reply/quote
      - name: created_at_date
        description: Date tweet was created
      - name: recorded_at_date
        description: Date tweet was recorded
      - name: created_at
        description: Timestamp of tweet creation
      - name: recorded_at
        description: Timestamp when tweet was recorded
      - name: refers_to_user_id
        description: User ID of the author of the referenced tweet

  - name: 03_political_hashtags_count
    description: >
      Aggregated statistics about hashtag usage in political contexts, focusing on
      hashtags used by at least one politician. Includes usage metrics and temporal data.
    columns:
      - name: hashtag
        description: The hashtag being analyzed (converted to lowercase)
      - name: usage_count
        description: Total number of times the hashtag was used
      - name: unique_users
        description: Number of unique users who used this hashtag
      - name: politician_users
        description: Number of politicians who used this hashtag
      - name: first_used_at
        description: First recorded usage timestamp
      - name: last_used_at
        description: Most recent usage timestamp
      - name: pct_political_users
        description: Percentage of users who are politicians (rounded to 2 decimals)
      - name: days_active
        description: Number of days between first and last usage

  - name: 01_political_users
    description: >
      Matches Twitter users with known German politicians based on either Twitter handle or user ID.
      Combines user information with political metadata from the EPI network.
    columns:
      - name: user_id
        description: Twitter user ID
      - name: screen_name
        description: Twitter username (lowercase)
      - name: name  
        description: Display name
      - name: description
        description: Profile description
      - name: location
        description: User location
      - name: url
        description: Profile URL
      - name: created_at
        description: Account creation timestamp
      - name: lang  
        description: Account language
      - name: recorded_at
        description: When user data was recorded
      - name: party
        description: Political party affiliation from EPI data
      - name: institution
        description: Political institution from EPI data
      - name: office
        description: Political office from EPI data
      - name: region
        description: Geographic region from EPI data
      - name: twitter_name
        description: Official Twitter name from EPI data
      - name: twitter_handle
        description: Official Twitter handle from EPI data (lowercase)
      - name: year_of_birth
        description: Birth year from EPI data
      - name: gender
        description: Gender from EPI data
      - name: wikidata_id
        description: Wikidata ID from EPI data

  - name: 02_politically_engaged_users
    description: >
      Identifies and categorizes politically engaged Twitter users based on their interactions
      with politicians and political content. Combines user data, political metadata, and
      interaction metrics to create a comprehensive view of political engagement.
    columns:
      - name: user_id
        description: Twitter user ID
      - name: screen_name
        description: Twitter username
      - name: name
        description: Display name
      - name: description
        description: Profile description
      - name: location
        description: User location
      - name: url
        description: Profile URL
      - name: created_at
        description: Account creation timestamp
      - name: lang
        description: Account language setting
      - name: recorded_at
        description: When user data was recorded
      - name: verified
        description: Whether the account is verified
      - name: followers_count
        description: Number of followers
      - name: friends_count
        description: Number of accounts being followed
      - name: listed_count
        description: Number of lists containing this user
      - name: statuses_count
        description: Total number of tweets by user
      - name: favourites_count
        description: Number of tweets liked by user
      - name: is_politician
        description: Boolean indicating if user is a matched politician
      - name: party
        description: Political party if politician
      - name: institution
        description: Political institution if politician
      - name: office
        description: Political office if politician
      - name: region
        description: Geographic region if politician
      - name: political_twitter_name
        description: Official Twitter name if politician
      - name: political_twitter_handle
        description: Official Twitter handle if politician
      - name: year_of_birth
        description: Birth year if politician
      - name: gender
        description: Gender if politician
      - name: wikidata_id
        description: Wikidata ID if politician
      - name: mentions_made_count
        description: Number of times user mentioned politicians
      - name: times_mentioned_count
        description: Number of times user was mentioned by politicians
      - name: direct_interactions_count
        description: Count of direct interactions with politicians
      - name: total_interactions
        description: Sum of all political interaction counts